global:
  scrape_interval: 15s

scrape_configs:
  - job_name: usuarios-veiculos
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8080"]
        labels:
          servico: service-track-usuarios-veiculos
