apiVersion: 1

contactPoints:

  - orgId: 1
    name: local
    receivers:
      - uid: local-webhook
        type: webhook
        settings:
          url: http://alerta-webhook:8080/alertas
          httpMethod: POST
        disableResolveMessage: false

policies:

  - orgId: 1
    receiver: local
    group_by: [alertname, severidade]
    group_wait: 30s
    group_interval: 2m
    repeat_interval: 1h
