apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-track-usuarios-veiculos

resources:
  - ../../base

components:
  - ../../componentes/redis-efemero
  - ../../componentes/nodeport

images:
  - name: servicetrack-usuarios-veiculos
    newName: 734564927706.dkr.ecr.us-east-1.amazonaws.com/servicetrack-hml-usuarios-veiculos
    newTag: b2213f51f6ceb420b4be2d66efc560fd1288696c

patches:
  - path: hpa-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: service-track-usuarios-veiculos-config
    literals:
      - ST_USU_REDIS_HOST=service-track-usuarios-veiculos-redis
      - ST_USU_REDIS_PORT=6379
      - ST_USU_DB_POOL_MAX=10
      - ST_USU_DB_POOL_MIN=2
      - ST_USU_LIMITE_VERIFICACAO=20
      - ST_USU_FORMATO_DE_LOG=logstash
