apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-track-usuarios-veiculos

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: service-track

images:
  - name: servicetrack-usuarios-veiculos
    newTag: latest
